### PR TITLE
[WIP] Display repos

### LINKED ISSUE #9: Be able to easily search through my repositories
Either by the repos being organised by organisation, or with a search and autocomplete functionality

- select field populated with a list of user's Github repos (front-end)
- on selecting a repo send request for issues within that repo
- Github API - https://developer.github.com/v3/repos/#list-your-repositories

### PR DESCRIPTION
**Pull request by shouston3**
Fixes #9 

**Summary**: The user should be able to see all repos after being authenticated.

This pr will include:
* Api setup based on [the wiki](https://github.com/gitodoro/gitodoro/wiki/Api)
* Simple setup of the [Bulma](http://bulma.io/) css framework as discussed [here](https://github.com/gitodoro/gitodoro/issues/5)
* Api tests (simple shot tests)
* Setup and initial testing with karma
* Cleanly mapping over the repos object and displaying the repos across the dom

### CODE REVIEW

**Comment by Jbarget** [comment]
@shouston3 I thought we need to get a list of all orgs before getting a list of repos?

**Comment by shouston3** [comment]
Changed in the wiki

**Comment by shouston3** [comment]
Why was this merged?

**Comment by Jbarget** [comment]
I think this was merged because the branch tidyUp contained all the commits from this PR

**Pull request merged**
